# Generated by Django 5.2.8 on 2025-12-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_acesso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acesso',
        ),
    ]
