# Generated by Django 5.2.8 on 2025-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_delete_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
